### ISSUE TITLE
Rankings not updating anymore

### ISSUE THREAD

**Issue by Stardox** [Brawlmance/Crawler#5]
Hi. Not sure if you are still maintaining this, but the player profiles within _Rankings_ section are no longer updating.It says that the last update was 27 days ago. See:
https://brawlmance.com/search?legend=14&brawlhalla_id=60596

Not sure if scheduled task / crawler stopped working. Can you take a look?

**Comment by NiciusB** [comment]
Hi! The crawler had indeed stopped working. I'll have to set up some health checks and alerting. Thanks for opening the issue!
